#!/usr/bin/env bash
set -euo pipefail

# IDP Portal — Installation Script
# Usage: ./setup.sh          (Docker mode, default)
#        ./setup.sh --native  (Native Node.js mode)

MODE="docker"
if [[ "${1:-}" == "--native" ]]; then
  MODE="native"
fi

echo ""
echo "==================================="
echo "  IDP Portal Setup"
echo "  Mode: $MODE"
echo "==================================="
echo ""

# ── Prerequisite checks ──────────────────────────────────────────

check_command() {
  if ! command -v "$1" &>/dev/null; then
    echo "ERROR: '$1' is required but not found. Please install it first."
    exit 1
  fi
}

if [[ "$MODE" == "docker" ]]; then
  check_command docker
  if ! docker compose version &>/dev/null; then
    echo "ERROR: 'docker compose' (v2) is required. Please install Docker Compose v2."
    exit 1
  fi
else
  check_command node
  check_command npm
  NODE_VERSION=$(node -v | sed 's/v//' | cut -d. -f1)
  if (( NODE_VERSION < 18 )); then
    echo "ERROR: Node.js v18+ is required (found v$NODE_VERSION)."
    exit 1
  fi
fi

# ── Generate secrets ─────────────────────────────────────────────

generate_jwt_secret() {
  if command -v openssl &>/dev/null; then
    openssl rand -base64 48
  else
    head -c 48 /dev/urandom | base64
  fi
}

generate_encryption_key() {
  if command -v openssl &>/dev/null; then
    openssl rand -hex 32
  else
    head -c 32 /dev/urandom | xxd -p | tr -d '\n'
  fi
}

# ── Create .env file ─────────────────────────────────────────────

ENV_FILE=".env"

if [[ -f "$ENV_FILE" ]]; then
  echo "Found existing $ENV_FILE — skipping generation."
  echo "(Delete it and re-run setup to regenerate.)"
  echo ""
else
  echo "Generating $ENV_FILE with secure secrets..."

  JWT_SECRET=$(generate_jwt_secret)
  ENCRYPTION_KEY=$(generate_encryption_key)

  read -rp "Port [3001]: " PORT
  PORT="${PORT:-3001}"

  read -rp "Server URL (public-facing, for SSO callbacks) [http://localhost:$PORT]: " SERVER_URL
  SERVER_URL="${SERVER_URL:-http://localhost:$PORT}"

  if [[ "$MODE" == "docker" ]]; then
    DB_URL="file:./data/idp.db"
  else
    DB_URL="file:./dev.db"
  fi

  cat > "$ENV_FILE" <<EOF
# Generated by setup.sh on $(date -Iseconds)
PORT=$PORT
NODE_ENV=production

JWT_SECRET=$JWT_SECRET
JWT_EXPIRES_IN=24h

ENCRYPTION_KEY=$ENCRYPTION_KEY

DATABASE_URL=$DB_URL

SERVER_URL=$SERVER_URL
EOF

  echo "Created $ENV_FILE"
  echo ""
fi

# ── Docker mode ──────────────────────────────────────────────────

if [[ "$MODE" == "docker" ]]; then
  echo "Building Docker image..."
  COMMIT_HASH=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
  export COMMIT_HASH
  docker compose build

  echo ""
  echo "Running database migrations..."
  docker compose run --rm idp-portal sh -c "cd server && npx prisma migrate dev --name init"

  echo ""
  echo "Seeding database..."
  docker compose run --rm idp-portal sh -c "cd server && npx tsx prisma/seed.ts"

  echo ""
  echo "Starting IDP Portal..."
  docker compose up -d

  PORT=$(grep -E '^PORT=' "$ENV_FILE" | cut -d= -f2)
  PORT="${PORT:-3001}"

  echo ""
  echo "==================================="
  echo "  IDP Portal is running!"
  echo "  URL: http://localhost:$PORT"
  echo "==================================="
  echo ""
  echo "First visit will prompt you to create an admin account."
  echo ""
  echo "Useful commands:"
  echo "  docker compose logs -f    # View logs"
  echo "  docker compose down       # Stop"
  echo "  docker compose up -d      # Start"
  echo ""

# ── Native mode ──────────────────────────────────────────────────

else
  echo "Installing dependencies..."
  npm ci

  echo ""
  echo "Building all packages..."
  npm run build

  echo ""
  echo "Running database migrations..."
  cd server && npx prisma migrate dev --name init && cd ..

  echo ""
  echo "Seeding database..."
  cd server && npx tsx prisma/seed.ts && cd ..

  PORT=$(grep -E '^PORT=' "$ENV_FILE" | cut -d= -f2)
  PORT="${PORT:-3001}"

  echo ""
  echo "==================================="
  echo "  IDP Portal is ready!"
  echo "==================================="
  echo ""
  echo "Start the production server:"
  echo "  NODE_ENV=production node server/dist/index.js"
  echo ""
  echo "Then visit: http://localhost:$PORT"
  echo "First visit will prompt you to create an admin account."
  echo ""
fi
